-- ============================================================
-- Seed Data
-- ============================================================
--
-- This file is intentionally kept free of fabricated landlords, properties,
-- reviews, or public records.
--
-- Vett should only be populated from:
-- 1. real user reviews that pass lease verification, and
-- 2. official public-record sync jobs in /api/sync/[source].
--
-- For local development, run the sync routes or insert your own clearly marked
-- test fixtures in a separate temporary script that never ships to production.
