import { NextRequest, NextResponse } from 'next/server'
import { createClient, createServiceClient } from '@/lib/supabase/server'

// Lease docs are stored under deterministic per-review keys generated by the
// upload helper. Tightening the accepted shape here is a defense-in-depth
// guard against an admin endpoint becoming an oracle for arbitrary
// lease-docs paths if the upload naming ever drifts. Real-world keys we
// generate look like `<review-id>/<filename>` or `<review-id>.<ext>`, so
// allow alphanumerics, dashes, underscores, dots, and a single forward
// slash separator. Reject empty segments and any traversal attempt.
const LEASE_PATH_RE = /^[a-zA-Z0-9_-]+(?:\.[a-zA-Z0-9]+|\/[a-zA-Z0-9._-]+)?$/

export async function GET(req: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: profile } = await supabase.from('profiles').select('user_type').eq('id', user.id).single()
  if (profile?.user_type !== 'admin') return NextResponse.json({ error: 'Forbidden' }, { status: 403 })

  const path = req.nextUrl.searchParams.get('path')
  if (!path) return NextResponse.json({ error: 'path required' }, { status: 400 })
  if (!LEASE_PATH_RE.test(path) || path.includes('..')) {
    return NextResponse.json({ error: 'Invalid path' }, { status: 400 })
  }

  // Use service client — private buckets need service role for signed URLs
  const serviceClient = createServiceClient()
  const { data, error } = await serviceClient.storage.from('lease-docs').createSignedUrl(path, 3600)
  if (error || !data) return NextResponse.json({ error: 'Could not generate URL' }, { status: 500 })

  // Return the URL as JSON so the client can open it
  return NextResponse.json({ signedUrl: data.signedUrl })
}
