export const PUBLIC_REVIEW_SELECT = `
  id,
  landlord_id,
  property_id,
  rating_overall,
  rating_responsiveness,
  rating_maintenance,
  rating_honesty,
  rating_lease_fairness,
  would_rent_again,
  title,
  body,
  rental_period_start,
  rental_period_end,
  is_current_tenant,
  lease_verified,
  landlord_response,
  landlord_response_at,
  landlord_response_status,
  helpful_count,
  flag_count,
  created_at,
  updated_at,
  reviewer:profiles(full_name, avatar_url),
  property:properties(address_line1, city, state_abbr)
`
